# Generated by Django 2.2.4 on 2019-08-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_extend',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
