# Generated by Django 2.2.4 on 2019-09-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='last',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
