# Generated by Django 2.2.4 on 2019-09-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courses_thumnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='thumnail',
            field=models.ImageField(upload_to='courses_image/'),
        ),
    ]
